### ISSUE TITLE
Feature request: Setting custom localization string keys

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-l10n#134] opened 2023-10-03 04:51 UTC
VS Code localization currently uses a hash of [English string] + [comment] as a key for localization strings in `.xlf` files. It would be beneficial to allow having a custom, stable key for each localization string. For example, if we make a small change to an English string that has already been translated, it would be good to keep the old translation for as long as it takes to re-translate the new version, instead of showing untranslated English strings during that period of time. Similarly, it could be useful to have the old translation at hand to use as a reference for the new translation.

In terms of implementation, the custom key could be provided as an optional parameter to the `vscode.l10n.t()` function and parsed by @vscode/l10n-dev together with the English strings and comments.

**Comment by TylerLeonhardt** [comment] 2023-10-03 16:37
This is a duplicate of https://github.com/microsoft/vscode/issues/193738

**Closed by TylerLeonhardt** 2023-10-03 16:37 UTC

**Comment by jruales** [comment] 2023-10-03 18:53
@TylerLeonhardt I apologize about the duplicate. I filtered by Issues created by me in this repo and didn't found the one I had posted so I thought I had accidentally discarded it before creating the issue. I didn't realize that I had created it in another repo. My bad. Thanks for linking to it from here.
