### ISSUE TITLE
l10n | New function l10n.k to manage translation by key instead of English natural text translation

### ISSUE THREAD

**Issue by FALLAI-Denis** [microsoft/vscode-l10n#152] opened 2023-12-16 13:12 UTC
Hi,

Extract from:
* #28 

The l10n solution based on the use of the natural language (English) as a search key for localization poses the problem that each change in text used as a search key for localization immediately has an impact on all bundle language files: a typography correction in the text used as a search key requires to modify all the bundle files of the proposed localization languages.

The l10n solution should at least offer a way to define key values, **truly neutral**, as for package.nls.json files, not linked to a particular language, with bundle files containing the texts for the different languages, including a default bundle that can be English for its universal aspect.

To limit the impacts on existing extensions, this could be implemented by offering a new function other than `l10n.t('text')` to manage searches by key and not searches by text, for example a `l10n.k('key')` function:

* the VS Code core must load at least one bundle file, either the one corresponding to current active language, `bundle.l10n.<locale>.json`, or the default bundle file (without explicit language), `bundle.l10n.json`,
* searching for the text associated with the key using `l10n.k('key')` must be done regardless of the active language, including English.

As summary, the difference between the two functions would be:
* `l10n.t('text')`: ignores the `bundle.l10n.json` file, and imposes the use of the English language in texts used in the extension, also imposes a definitive version of the texts used in the extension
* `l10n.k('key')`: takes into account the `bundle.l10n.json` file, and does not impose the use of the English language in the texts used in the extension, which also allows deferring and delegating translation to different translators

See also:
* [Support for different default language](https://github.com/microsoft/vscode/issues/168127) #168127

Thanks.

**Comment by TylerLeonhardt** [comment] 2023-12-17 05:48
Instead of a new function, I think something like this would be better:

```ts
l10n.t({ key: 'somekey' });
```

This would also allow for:

```ts
l10n.t({
  key: 'somekey',
  message: 'same message property that already exists'
});
```

which is an ask we have here https://github.com/microsoft/vscode/issues/193738

**Comment by TylerLeonhardt** [comment] 2023-12-18 18:15
Marking this as a duplicate of https://github.com/microsoft/vscode/issues/193738

**Closed by TylerLeonhardt** 2023-12-18 18:15 UTC
